### ISSUE TITLE
question: connect to first node?

### ISSUE THREAD

**Issue by smolleyes** [janoside/lnd-admin#35]
hi

sorry for the dumb question but i don t know where to get this first node to connect to ?

Add LND Node

File Input
Raw Text Input
LND Connect

where can i get the info or extra doc on the setup...  :) ? thanks!

**Comment by janoside** [comment]
No problem. You'll need to run your own LND node first. Check out the README for this project and see the first item under "Getting Started". That item links to the installation instructions for LND (made by Lightning Labs).

For your convenience, here is the link again: https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md - You can also see other background information about LND in their main project README: https://github.com/lightningnetwork/lnd

**Comment by smolleyes** [comment]
ok will have a look , thanks !

**Comment by smolleyes** [comment]
https://gist.github.com/bretton/266b5a3902cd8e1a2b9776b878e5652d

a bit more clear to me ;) i m syncing now, thanks
